### ISSUE TITLE
Wine Ratings

### ISSUE THREAD

**Issue by aylapear** [UBC-MDS/DSCI_522_payla_rzitomer#1]
About the Scores

Ratings reflect what our editors felt about a particular product. Beyond the rating, we encourage you to read the accompanying tasting note to learn about a product’s special characteristics.

98–100 Classic The pinnacle of quality.
94–97 Superb A great achievement.
90–93 Excellent Highly recommended.
87–89 Very Good Often good value; well recommended.
83–86 Good Suitable for everyday consumption; often good value.
80–82 Acceptable Can be employed in casual, less-critical circumstances.

Products deemed Unacceptable (receiving a rating below 80 points) are not reviewed.

Source: https://www.winemag.com/buying-guide/patland-2013-stagecoach-vineyard-select-barrel-reserve-cabernet-sauvignon-napa-valley/

**Comment by rzitomer** [comment]
This is perfect! Do you want to just predict whether or not a wine is a Classic? We could also just predict each category.

**Comment by rzitomer** [comment]
Our original question had the cutoff at 90, we could also leave it there, so we're dividing our dataset between Acceptable through Very Good and Excellent through Classic.
