### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/DSCI_522_payla_rzitomer#10]
__Mechanics__

* The 'proposal', i.e. the answers to 1-4 should be documented in README of the project repo as per lab instructions. 

* Also, could have changed the title in README to a more meaningful project name. 

__Reasoning__

* For 3. analysis plan, could have elaborated more on how you are going to carry out the steps in addition to listing what steps will be taken. For example, how would you carry out feature engineering for this particular task and dataset? How would you convert the categorical variables for decision trees? I can think of binning a continuous variable to categorical/ordinal data -- transforming from a higher resolution to a lower resolution, maybe for ease of comparison across group in the context of regression -- but not sure what we can do with categorical ones in general. 

__Other comments__

* Just for my curiosity, how did you choose the cutoff of 98 points? I wonder what is the proportion of wine in the data that scored 98+."

**Comment by rzitomer** [comment]
Mechanics
- We've added the proposal to the README
- We changed the title to be more meaningful

Reasoning
- We've answered these questions by elaborating on the README. From our updated step 2:

> - feature engineering
    - Drop features we don't plan on using because they would not be good predictors (e.g. >90% of the wines have different
    titles so that column won't generalize to new data points) or they're not relevant to the spirit of our question (e.g.
    the twitter handler of the WineEnthusiast taster who wrote the review could end up being predictive of review score,
    but it won't help an audience understand which wine to buy). 
    - Convert categorical variables to a format that can be used for decision trees
        - We chose to do this by one_hot_encoding (due to the limitations of the decision tree classifier in scikit-learn, 
        which can't handle categorical variables)
> - make a binary column based on points as the dependent variable to be predicted
    - Make a column called `greater_than_90`
    - if the points column is 90 or greater then label the value for the row to be `True`
    - if the points column is less than or equal to 90 points then label the value for the row to be `False`

Other Comments:
- Yeah 98+ ended up being a bad choice, so we changed it to 90+. For more on our thinking, see here (from our results file): 
> Why did we choose this exact question? We knew from the beginning that we were going to use these ratings to determine what features make a wine particularly likely to be good. We originally were going to fit a model that would predict whether or not a wine was "Classic," but in the original dataset <.1% of wine was categorized as such, so we knew we would have a class imbalance problem. We considered fitting a model to predict whether a wine's rating would be above or below the median score in the dataset, which would ensure we would never have a class imbalance problem and would help us understand what makes a wine better or worse than average. Ultimiately, we decided to predict whether or not a wine was greater than or equal to 90. This has the advantage of both mapping to WineEnthusiast's categorical ratings (the model will predict whether a wine was at least "Excellent"" or not) and it also splits the classes fairly evenly (~38% of wine in the original dataset had a rating >= 90).
