### ISSUE TITLE
How to load the dataset?

### ISSUE THREAD

**Issue by aylapear** [UBC-MDS/DSCI_522_payla_rzitomer#2]
To finish question 1 in the proposal we still have to do this part "Prove to us that you can load the data set into R or Python (this could be demonstrating by writing a script that downloads the data and saves a snippet of it, for example)". 

I assume these are our two main options:
1. download data and place in a data folder
2. read it in from a url 

I already did option 1 but the files are relatively large and github got upset with me but it did work. 

I dont know how to do option 2 from kaggle. I did a bit of googling but wasn't able to find anything helpful. 

Let me know if you want to do option 1 or 2.  If we go with option 2 I will delete the data files before sending my pull request.

It should only take a second to write the import statements, then we can take a snip shot of the code and head of the data and embed it in the proposal doc.

**Comment by rzitomer** [comment]
I would vote option 1, at least for now. I used their API to download the data, but that just got me the same thing (it downloaded a ~50mb zip file locally) and if we did that in our repo (have part of the script be downloading the data from our API) we'd also have to manage API key permissions. Doesn't look like theres a way to read this in directly from a url.

One reason the overall zip file is so large is that theres several versions of the same files here in different formats (json and csv). We only need to download the most recent version in a CSV format (winemag-data-130k-V2.csv). The file is only (😬) ~17mb zipped, will github get upset with that size? Also you can keep it zipped and once you send the pull request I can unzip it as part of the import statements.

**Comment by aylapear** [comment]
I had already unzipped it, but the one file isn't too bad once I deleted the other ones. Feel free to change it to the zipped. It got upset at 50MB and it is 50.5 so, I think it will be ok. It didn't say no, it was just a warning it was getting large.
