### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by rzitomer** [UBC-MDS/DSCI_522_payla_rzitomer#21]
- Graphs that show spread of categorical labels
      - e.g. how many wines were classic, how many were excellent, etc. 
- Change bar graphs for country and variety to show distribution (boxplot or violin + jitter?)
- Show training accuracy on graphs where you choose hyper-parameters
- Predict every class (e.g. classic, excellent, etc.), not just above or below 90
- Is there variation among wine tasters?

**Comment by aylapear** [comment]
- the training accuracy has been added to model_depth_decision.png

**Comment by rzitomer** [comment]
- "Graphs that show spread of categorical labels"
Added: b937ae1e9792fa4c614b09b517685a8430faf46e

**Comment by rzitomer** [comment]
"Is there variation among wine tasters?"
Added this question to the limitation section 10a60bacd1d4e0dfcca91fe9500f168cb2ece59c
