### ISSUE TITLE
Make all outputs of src/decision_tree.py depend on the output_file argument

### ISSUE THREAD

**Issue by rzitomer** [UBC-MDS/DSCI_522_payla_rzitomer#25]
@aylapear right now a few of the outputs in decision_tree.py have hardcoded file paths (e.g. 'results/depth_decision.png' in line 61). I think it would make sense for all outputs of src/decision_tree.py depend on output_file argument, so if someone has a different directory they're outputting everything else to they could also output those graphs there.

**Comment by aylapear** [comment]
I believe I have fixed this. I have updated the README, script ex within script, and Makefile.
